import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import TrayHandler from "./components/TrayHandler";
import NotificationProvider from "./components/NotificationProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Abang Malaysia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}
      >
        <NotificationProvider>
          <Navbar />
          <TrayHandler />
          <main className="pt-16">
            {children}
          </main>
        </NotificationProvider>
      </body>
    </html>
  );
}

// app/layout.tsx
// import React from "react";
// import "./globals.css"; // or your global styles

// export const metadata = {
//     title: "Your App Title",
//     description: "App description here",
// };

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//     return (
//         <html lang="en">
//             <body>{children}</body>
//         </html>
//     );
// }
